# Generated by Django 5.1.5 on 2025-01-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token_autenticate',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
