# Generated by Django 5.1.5 on 2025-01-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_token_autenticate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='token_autenticate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
