# Generated by Django 5.1.5 on 2025-01-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_from', models.CharField(max_length=40)),
                ('arriving_in', models.CharField(max_length=40)),
                ('starting_from_datetime', models.DateTimeField()),
                ('arriving_in_datetime', models.DateTimeField()),
                ('finished', models.BooleanField()),
            ],
        ),
    ]
