# Generated by Django 5.1.5 on 2025-01-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='travel',
            table='travel',
        ),
    ]
