# Generated by Django 5.1.5 on 2025-01-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_travel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='arriving_in_datetime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='starting_from_datetime',
            field=models.DateField(),
        ),
    ]
