# Generated by Django 5.1.5 on 2025-01-27 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_travel_arriving_in_datetime_and_more'),
        ('users', '0006_alter_users_token_autenticate'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.users'),
            preserve_default=False,
        ),
    ]
